### PR TITLE
Anniversary special-pyDelhi and blockchainDevs

### PR DESCRIPTION
**Pull request by rashigupta1611**

### CODE REVIEW

**Comment by realslimshanky** [comment]
@rashigupta1611 we have a blog for the same meetup here https://github.com/pydelhi/blog/pull/29
I suggest we should merge the content of this PR as well with that one.

**Comment by rashigupta1611** [comment]
How can i do that?
Coz i feel that there should be little ammendments  in the other blog

**Comment by Kaushl2208** [comment]
@rashigupta1611 you can request changes on my PR and I can update that with whatever it needs. Looking forward for your reviews . Link to my PR is mentioned here! [#29](https://github.com/pydelhi/blog/pull/29)

**Comment by aaqaishtyaq** [comment]
Since #29 already merged and live, I'm closing this PR.

**Pull request closed without merging**
