### PR TITLE
Added blog for the pydelhi-devsprint held on 02-02-2019

### PR DESCRIPTION
**Pull request by ayushi-1972**
Amazing learning experience!All the changes have been made in the blog successfully.

### CODE REVIEW

**Review by akshayaurora — APPROVED** [review]

**Review by realslimshanky — COMMENTED** [review]
Can you please rename the images to reflect which blog they belong to? For ex you can include the date/name of the content .md file

**Comment by ayushi-1972** [comment]
Sure!!

**Review by realslimshanky — COMMENTED** [review]
Please delete unnecessary files
- https://github.com/pydelhi/blog/pull/32/files#diff-e14f0c8186cb30e8914a7087459c8181
- https://github.com/pydelhi/blog/pull/32/files#diff-32fea67c6380911828291aafe664beb7

**Review by realslimshanky — APPROVED** [review]

**Comment by realslimshanky** [comment]
Thank you @ayushi-1972 for taking all the effort of adding this blog.

**Pull request merged**
